### ISSUE TITLE
Plain text in php and JS files

### ISSUE THREAD

**Issue by volodymyrdovhan** [NicoAlexH/moodle-tiny_corrections#1]
Hello,
I found plain text, which should be defined in language files, in some PHP and Js files:

![image](https://github.com/user-attachments/assets/6a4e7d03-64f1-491e-8b1d-a5b2916ec202)

![image](https://github.com/user-attachments/assets/6c25aed3-491f-46e8-b9ac-64d7ad192b07)

**Comment by NicoAlexH** [comment]
Hi @volodymyrdovhan,
Thanks for the heads up, I replaced the hardcoded text with localised strings in https://github.com/NicoAlexH/moodle-tiny_corrections/commit/5fa3f691cf24b4c537813d6830bbde08a8dae268
