### ISSUE TITLE
Adding editor screenshots

### ISSUE THREAD

**Issue by volodymyrdovhan** [NicoAlexH/moodle-tiny_corrections#2]
Hello,
Could you please upload a screenshot of the editor that demonstrates how the plugin’s buttons appear? This will help users locate them more quickly.

![image](https://github.com/user-attachments/assets/6b2447e9-50f1-4542-bc41-89c8f78091e4)

**Comment by NicoAlexH** [comment]
Hi @volodymyrdovhan, sure, I updated the README file ; I hope it is a bit clearer now. Thank you for the suggestion (and for the screenshot :) )
